"""兼容旧导入路径的本地 Prompt 常量。"""

from app.ai.prompts.local_templates import CODE_DEFAULT_PROMPT_TEMPLATES

GENERATE_TITLE_PROMPT = CODE_DEFAULT_PROMPT_TEMPLATES["generate_title"]
GENERATE_SUGGESTED_QUESTIONS_PROMPT = CODE_DEFAULT_PROMPT_TEMPLATES["generate_suggested_questions"]
FILE_ANALYSIS_PROMPT = CODE_DEFAULT_PROMPT_TEMPLATES["file_analysis"]
FILE_CONTENT_ENHANCEMENT_PROMPT = CODE_DEFAULT_PROMPT_TEMPLATES["file_content_enhancement"]
