"""共享地名词表：Run 能力路由与计划工具策略的唯一事实源。

此前中文名单在 `agent_plan_tool_policy` 内、英文名单在 `run_capability_router` 内各维护
一份，两份互不同步（英文有 harbin/sanya，中文没有哈尔滨/三亚），导致同一个请求换语言
就换结果。这里统一为一份数据，并按行政区划一次性补全，而不是按失败用例逐条追加。

词表只用于**提升置信度**：命中表示端点确定是地名；未命中不代表不是地名，调用方必须
另有兜底路径（见 `agent_plan_tool_policy._endpoint_slot_tier`）。
"""

from __future__ import annotations

# 中国地级及以上行政区（含直辖市、自治州、地区、盟），按省级单位分组，便于核对与补充。
_CHINA_CITY_NAMES_BY_PROVINCE: dict[str, tuple[str, ...]] = {
    "直辖市": ("北京", "天津", "上海", "重庆"),
    "河北": (
        "石家庄",
        "唐山",
        "秦皇岛",
        "邯郸",
        "邢台",
        "保定",
        "张家口",
        "承德",
        "沧州",
        "廊坊",
        "衡水",
    ),
    "山西": (
        "太原",
        "大同",
        "阳泉",
        "长治",
        "晋城",
        "朔州",
        "晋中",
        "运城",
        "忻州",
        "临汾",
        "吕梁",
    ),
    "内蒙古": (
        "呼和浩特",
        "包头",
        "乌海",
        "赤峰",
        "通辽",
        "鄂尔多斯",
        "呼伦贝尔",
        "巴彦淖尔",
        "乌兰察布",
        "兴安",
        "锡林郭勒",
        "阿拉善",
    ),
    "辽宁": (
        "沈阳",
        "大连",
        "鞍山",
        "抚顺",
        "本溪",
        "丹东",
        "锦州",
        "营口",
        "阜新",
        "辽阳",
        "盘锦",
        "铁岭",
        "朝阳",
        "葫芦岛",
    ),
    "吉林": ("长春", "吉林", "四平", "辽源", "通化", "白山", "松原", "白城", "延边"),
    "黑龙江": (
        "哈尔滨",
        "齐齐哈尔",
        "鸡西",
        "鹤岗",
        "双鸭山",
        "大庆",
        "伊春",
        "佳木斯",
        "七台河",
        "牡丹江",
        "黑河",
        "绥化",
        "大兴安岭",
    ),
    "江苏": (
        "南京",
        "无锡",
        "徐州",
        "常州",
        "苏州",
        "南通",
        "连云港",
        "淮安",
        "盐城",
        "扬州",
        "镇江",
        "泰州",
        "宿迁",
    ),
    "浙江": (
        "杭州",
        "宁波",
        "温州",
        "嘉兴",
        "湖州",
        "绍兴",
        "金华",
        "衢州",
        "舟山",
        "台州",
        "丽水",
    ),
    "安徽": (
        "合肥",
        "芜湖",
        "蚌埠",
        "淮南",
        "马鞍山",
        "淮北",
        "铜陵",
        "安庆",
        "黄山",
        "滁州",
        "阜阳",
        "宿州",
        "六安",
        "亳州",
        "池州",
        "宣城",
    ),
    "福建": ("福州", "厦门", "莆田", "三明", "泉州", "漳州", "南平", "龙岩", "宁德"),
    "江西": (
        "南昌",
        "景德镇",
        "萍乡",
        "九江",
        "新余",
        "鹰潭",
        "赣州",
        "吉安",
        "宜春",
        "抚州",
        "上饶",
    ),
    "山东": (
        "济南",
        "青岛",
        "淄博",
        "枣庄",
        "东营",
        "烟台",
        "潍坊",
        "济宁",
        "泰安",
        "威海",
        "日照",
        "临沂",
        "德州",
        "聊城",
        "滨州",
        "菏泽",
    ),
    "河南": (
        "郑州",
        "开封",
        "洛阳",
        "平顶山",
        "安阳",
        "鹤壁",
        "新乡",
        "焦作",
        "濮阳",
        "许昌",
        "漯河",
        "三门峡",
        "南阳",
        "商丘",
        "信阳",
        "周口",
        "驻马店",
        "济源",
    ),
    "湖北": (
        "武汉",
        "黄石",
        "十堰",
        "宜昌",
        "襄阳",
        "鄂州",
        "荆门",
        "孝感",
        "荆州",
        "黄冈",
        "咸宁",
        "随州",
        "恩施",
    ),
    "湖南": (
        "长沙",
        "株洲",
        "湘潭",
        "衡阳",
        "邵阳",
        "岳阳",
        "常德",
        "张家界",
        "益阳",
        "郴州",
        "永州",
        "怀化",
        "娄底",
        "湘西",
    ),
    "广东": (
        "广州",
        "韶关",
        "深圳",
        "珠海",
        "汕头",
        "佛山",
        "江门",
        "湛江",
        "茂名",
        "肇庆",
        "惠州",
        "梅州",
        "汕尾",
        "河源",
        "阳江",
        "清远",
        "东莞",
        "中山",
        "潮州",
        "揭阳",
        "云浮",
    ),
    "广西": (
        "南宁",
        "柳州",
        "桂林",
        "梧州",
        "北海",
        "防城港",
        "钦州",
        "贵港",
        "玉林",
        "百色",
        "贺州",
        "河池",
        "来宾",
        "崇左",
    ),
    "海南": ("海口", "三亚", "三沙", "儋州"),
    "四川": (
        "成都",
        "自贡",
        "攀枝花",
        "泸州",
        "德阳",
        "绵阳",
        "广元",
        "遂宁",
        "内江",
        "乐山",
        "南充",
        "眉山",
        "宜宾",
        "广安",
        "达州",
        "雅安",
        "巴中",
        "资阳",
        "阿坝",
        "甘孜",
        "凉山",
    ),
    "贵州": ("贵阳", "六盘水", "遵义", "安顺", "毕节", "铜仁", "黔西南", "黔东南", "黔南"),
    "云南": (
        "昆明",
        "曲靖",
        "玉溪",
        "保山",
        "昭通",
        "丽江",
        "普洱",
        "临沧",
        "楚雄",
        "红河",
        "文山",
        "西双版纳",
        "大理",
        "德宏",
        "怒江",
        "迪庆",
    ),
    "西藏": ("拉萨", "日喀则", "昌都", "林芝", "山南", "那曲", "阿里"),
    "陕西": ("西安", "铜川", "宝鸡", "咸阳", "渭南", "延安", "汉中", "榆林", "安康", "商洛"),
    "甘肃": (
        "兰州",
        "嘉峪关",
        "金昌",
        "白银",
        "天水",
        "武威",
        "张掖",
        "平凉",
        "酒泉",
        "庆阳",
        "定西",
        "陇南",
        "临夏",
        "甘南",
    ),
    "青海": ("西宁", "海东", "海北", "黄南", "果洛", "玉树", "海西"),
    "宁夏": ("银川", "石嘴山", "吴忠", "固原", "中卫"),
    "新疆": (
        "乌鲁木齐",
        "克拉玛依",
        "吐鲁番",
        "哈密",
        "昌吉",
        "博尔塔拉",
        "巴音郭楞",
        "阿克苏",
        "克孜勒苏",
        "喀什",
        "和田",
        "伊犁",
        "塔城",
        "阿勒泰",
        "石河子",
    ),
    "港澳台": ("香港", "澳门", "台北", "新北", "桃园", "台中", "台南", "高雄", "基隆", "新竹"),
}

# 常见境外城市：出行请求同样会跨境，仅收录高频目的地。
_OVERSEAS_CITY_NAMES: tuple[str, ...] = (
    "东京",
    "大阪",
    "京都",
    "名古屋",
    "札幌",
    "福冈",
    "冲绳",
    "首尔",
    "釜山",
    "济州",
    "曼谷",
    "清迈",
    "普吉",
    "芭提雅",
    "新加坡",
    "吉隆坡",
    "槟城",
    "雅加达",
    "巴厘岛",
    "马尼拉",
    "长滩岛",
    "河内",
    "岘港",
    "胡志明",
    "金边",
    "万象",
    "仰光",
    "新德里",
    "孟买",
    "班加罗尔",
    "加德满都",
    "科伦坡",
    "达卡",
    "伊斯兰堡",
    "迪拜",
    "多哈",
    "伊斯坦布尔",
    "特拉维夫",
    "开罗",
    "约翰内斯堡",
    "内罗毕",
    "莫斯科",
    "圣彼得堡",
    "伦敦",
    "曼彻斯特",
    "爱丁堡",
    "都柏林",
    "巴黎",
    "尼斯",
    "柏林",
    "慕尼黑",
    "法兰克福",
    "汉堡",
    "阿姆斯特丹",
    "布鲁塞尔",
    "苏黎世",
    "日内瓦",
    "维也纳",
    "布拉格",
    "布达佩斯",
    "华沙",
    "罗马",
    "米兰",
    "威尼斯",
    "佛罗伦萨",
    "巴塞罗那",
    "马德里",
    "里斯本",
    "雅典",
    "斯德哥尔摩",
    "奥斯陆",
    "哥本哈根",
    "赫尔辛基",
    "雷克雅未克",
    "纽约",
    "洛杉矶",
    "旧金山",
    "芝加哥",
    "西雅图",
    "波士顿",
    "华盛顿",
    "拉斯维加斯",
    "迈阿密",
    "檀香山",
    "温哥华",
    "多伦多",
    "蒙特利尔",
    "墨西哥城",
    "圣保罗",
    "里约热内卢",
    "布宜诺斯艾利斯",
    "利马",
    "圣地亚哥",
    "悉尼",
    "墨尔本",
    "布里斯班",
    "珀斯",
    "堪培拉",
    "奥克兰",
    "惠灵顿",
)

KNOWN_LOCATION_NAMES: frozenset[str] = frozenset(
    name for names in _CHINA_CITY_NAMES_BY_PROVINCE.values() for name in names
) | frozenset(_OVERSEAS_CITY_NAMES)

# 中文知名地标：与城市名一起构成"确定是地点"的正向信号。
KNOWN_LANDMARK_NAMES: frozenset[str] = frozenset(
    {
        "故宫",
        "天安门",
        "颐和园",
        "长城",
        "圆明园",
        "鸟巢",
        "水立方",
        "外滩",
        "东方明珠",
        "迪士尼",
        "陆家嘴",
        "南京路",
        "西湖",
        "兵马俑",
        "大雁塔",
        "黄鹤楼",
        "岳麓山",
        "珠江新城",
        "奥体中心",
        "市民中心",
        "会展中心",
        "环球影城",
    }
)

# 英文/拼音地名：与中文表镜像，供英文请求路由使用（全部小写）。
EN_KNOWN_LOCATION_NAMES: frozenset[str] = frozenset(
    {
        "beijing",
        "tianjin",
        "shanghai",
        "chongqing",
        "shijiazhuang",
        "tangshan",
        "qinhuangdao",
        "handan",
        "baoding",
        "zhangjiakou",
        "langfang",
        "taiyuan",
        "datong",
        "changzhi",
        "hohhot",
        "baotou",
        "chifeng",
        "ordos",
        "hulunbuir",
        "shenyang",
        "dalian",
        "anshan",
        "fushun",
        "dandong",
        "jinzhou",
        "yingkou",
        "changchun",
        "jilin",
        "yanbian",
        "harbin",
        "qiqihar",
        "daqing",
        "mudanjiang",
        "nanjing",
        "wuxi",
        "xuzhou",
        "changzhou",
        "suzhou",
        "nantong",
        "lianyungang",
        "huaian",
        "yancheng",
        "yangzhou",
        "zhenjiang",
        "taizhou",
        "suqian",
        "hangzhou",
        "ningbo",
        "wenzhou",
        "jiaxing",
        "huzhou",
        "shaoxing",
        "jinhua",
        "quzhou",
        "zhoushan",
        "lishui",
        "hefei",
        "wuhu",
        "bengbu",
        "maanshan",
        "anqing",
        "huangshan",
        "fuyang",
        "luan",
        "fuzhou",
        "xiamen",
        "putian",
        "sanming",
        "quanzhou",
        "zhangzhou",
        "nanping",
        "longyan",
        "ningde",
        "nanchang",
        "jingdezhen",
        "jiujiang",
        "ganzhou",
        "jian",
        "yichun",
        "shangrao",
        "jinan",
        "qingdao",
        "zibo",
        "zaozhuang",
        "dongying",
        "yantai",
        "weifang",
        "jining",
        "taian",
        "weihai",
        "rizhao",
        "linyi",
        "dezhou",
        "liaocheng",
        "binzhou",
        "heze",
        "zhengzhou",
        "kaifeng",
        "luoyang",
        "anyang",
        "xinxiang",
        "jiaozuo",
        "xuchang",
        "nanyang",
        "shangqiu",
        "xinyang",
        "zhoukou",
        "wuhan",
        "huangshi",
        "shiyan",
        "yichang",
        "xiangyang",
        "ezhou",
        "jingmen",
        "xiaogan",
        "jingzhou",
        "huanggang",
        "xianning",
        "enshi",
        "changsha",
        "zhuzhou",
        "xiangtan",
        "hengyang",
        "shaoyang",
        "yueyang",
        "changde",
        "zhangjiajie",
        "yiyang",
        "chenzhou",
        "yongzhou",
        "huaihua",
        "loudi",
        "guangzhou",
        "shaoguan",
        "shenzhen",
        "zhuhai",
        "shantou",
        "foshan",
        "jiangmen",
        "zhanjiang",
        "maoming",
        "zhaoqing",
        "huizhou",
        "meizhou",
        "shanwei",
        "heyuan",
        "yangjiang",
        "qingyuan",
        "dongguan",
        "zhongshan",
        "chaozhou",
        "jieyang",
        "yunfu",
        "nanning",
        "liuzhou",
        "guilin",
        "wuzhou",
        "beihai",
        "qinzhou",
        "guigang",
        "yulin",
        "baise",
        "hezhou",
        "hechi",
        "laibin",
        "chongzuo",
        "haikou",
        "sanya",
        "danzhou",
        "chengdu",
        "zigong",
        "panzhihua",
        "luzhou",
        "deyang",
        "mianyang",
        "guangyuan",
        "suining",
        "neijiang",
        "leshan",
        "nanchong",
        "meishan",
        "yibin",
        "guangan",
        "dazhou",
        "yaan",
        "bazhong",
        "ziyang",
        "aba",
        "garze",
        "liangshan",
        "guiyang",
        "liupanshui",
        "zunyi",
        "anshun",
        "bijie",
        "tongren",
        "kunming",
        "qujing",
        "yuxi",
        "baoshan",
        "zhaotong",
        "lijiang",
        "puer",
        "lincang",
        "chuxiong",
        "honghe",
        "wenshan",
        "xishuangbanna",
        "dali",
        "dehong",
        "lhasa",
        "shigatse",
        "chamdo",
        "nyingchi",
        "shannan",
        "nagqu",
        "ngari",
        "xian",
        "xi'an",
        "tongchuan",
        "baoji",
        "xianyang",
        "weinan",
        "yanan",
        "hanzhong",
        "yulin",
        "ankang",
        "shangluo",
        "lanzhou",
        "jiayuguan",
        "jinchang",
        "baiyin",
        "tianshui",
        "wuwei",
        "zhangye",
        "pingliang",
        "jiuquan",
        "qingyang",
        "dingxi",
        "longnan",
        "xining",
        "haidong",
        "golmud",
        "yinchuan",
        "shizuishan",
        "wuzhong",
        "guyuan",
        "zhongwei",
        "urumqi",
        "karamay",
        "turpan",
        "hami",
        "changji",
        "aksu",
        "kashgar",
        "hotan",
        "yili",
        "tacheng",
        "altay",
        "shihezi",
        "hong kong",
        "hongkong",
        "macau",
        "macao",
        "taipei",
        "new taipei",
        "taoyuan",
        "taichung",
        "tainan",
        "kaohsiung",
        "keelung",
        "hsinchu",
        "tokyo",
        "osaka",
        "kyoto",
        "nagoya",
        "sapporo",
        "fukuoka",
        "okinawa",
        "seoul",
        "busan",
        "jeju",
        "bangkok",
        "chiang mai",
        "chiangmai",
        "phuket",
        "pattaya",
        "singapore",
        "kuala lumpur",
        "penang",
        "jakarta",
        "bali",
        "manila",
        "hanoi",
        "da nang",
        "danang",
        "ho chi minh",
        "phnom penh",
        "vientiane",
        "yangon",
        "new delhi",
        "delhi",
        "mumbai",
        "bangalore",
        "kathmandu",
        "colombo",
        "dhaka",
        "islamabad",
        "dubai",
        "doha",
        "istanbul",
        "tel aviv",
        "cairo",
        "johannesburg",
        "nairobi",
        "moscow",
        "saint petersburg",
        "london",
        "manchester",
        "edinburgh",
        "dublin",
        "paris",
        "nice",
        "berlin",
        "munich",
        "frankfurt",
        "hamburg",
        "amsterdam",
        "brussels",
        "zurich",
        "geneva",
        "vienna",
        "prague",
        "budapest",
        "warsaw",
        "rome",
        "milan",
        "venice",
        "florence",
        "barcelona",
        "madrid",
        "lisbon",
        "athens",
        "stockholm",
        "oslo",
        "copenhagen",
        "helsinki",
        "reykjavik",
        "new york",
        "los angeles",
        "san francisco",
        "chicago",
        "seattle",
        "boston",
        "washington",
        "las vegas",
        "miami",
        "honolulu",
        "vancouver",
        "toronto",
        "montreal",
        "mexico city",
        "sao paulo",
        "rio de janeiro",
        "buenos aires",
        "lima",
        "santiago",
        "sydney",
        "melbourne",
        "brisbane",
        "perth",
        "canberra",
        "auckland",
        "wellington",
    }
)

EN_KNOWN_LANDMARK_NAMES: frozenset[str] = frozenset(
    {
        "the bund",
        "the forbidden city",
        "forbidden city",
        "tiananmen",
        "the summer palace",
        "summer palace",
        "the great wall",
        "great wall",
        "people's square",
        "peoples square",
        "lujiazui",
        "disneyland",
        "west lake",
        "terracotta army",
        "hongqiao station",
        "shanghai hongqiao station",
        "hongqiao airport",
        "pudong airport",
        "grand central station",
        "city hall",
        "downtown",
        "city center",
    }
)

# 行政区后缀：`北京市` 与 `北京` 必须等价，`浦东新区外滩` 前缀不得让地标失配。
ADMIN_DIVISION_SUFFIXES: tuple[str, ...] = ("省", "市", "区", "县", "镇", "乡", "街道", "自治州", "地区", "盟")

# 交通枢纽后缀：只有这些后缀才允许把 `广州南站` 归到 `广州`，`北京大学` 不在其列。
_TRANSPORT_HUB_SUFFIXES: tuple[str, ...] = (
    "站",
    "机场",
    "码头",
    "港",
    "客运站",
    "航站楼",
    "枢纽",
)


def normalize_location_name(value: str) -> str:
    """剥掉行政区后缀与上级行政区前缀，得到可用于词表比对的裸地名。

    `北京市`、`广东省佛山市`、`浙江省金华` 都应归一到词表里的城市名。
    """

    normalized = value.strip()
    for _ in range(len(ADMIN_DIVISION_SUFFIXES)):
        stripped = _strip_one_admin_suffix(normalized)
        if stripped == normalized:
            break
        normalized = stripped
        if normalized in KNOWN_LOCATION_NAMES:
            return normalized
    if normalized in KNOWN_LOCATION_NAMES:
        return normalized
    return _strip_parent_division_prefix(normalized)


def _strip_one_admin_suffix(value: str) -> str:
    for suffix in ADMIN_DIVISION_SUFFIXES:
        candidate = value.removesuffix(suffix)
        if candidate and candidate != value:
            return candidate
    return value


def _strip_parent_division_prefix(value: str) -> str:
    """`广东省佛山` → `佛山`：上级行政区前缀不影响城市识别。"""

    for city in KNOWN_LOCATION_NAMES:
        if value == city or not value.endswith(city):
            continue
        prefix = value[: -len(city)]
        if prefix.endswith(ADMIN_DIVISION_SUFFIXES) or prefix in KNOWN_LOCATION_NAMES:
            return city
    return value


def is_known_city_name(value: str) -> bool:
    """只判定城市级地名；地标、车站、机场不算。

    区分跨城与同城出行时必须用它而不是 `is_known_location_name`：
    `上海虹桥站` 与 `外滩` 都是确定地点，但两者之间是同城路线。
    """

    if not value:
        return False
    if normalize_location_name(value) in KNOWN_LOCATION_NAMES:
        return True
    return value.strip().lower() in EN_KNOWN_LOCATION_NAMES


def is_known_location_name(value: str) -> bool:
    """中英文统一入口：命中城市或地标词表即视为确定地名。"""

    if not value:
        return False
    normalized = normalize_location_name(value)
    if normalized in KNOWN_LOCATION_NAMES or normalized in KNOWN_LANDMARK_NAMES:
        return True
    lowered = value.strip().lower()
    return lowered in EN_KNOWN_LOCATION_NAMES or lowered in EN_KNOWN_LANDMARK_NAMES


def resolve_city_key(value: str) -> str | None:
    """取出端点所属的城市；无法确定时返回 None。

    `广州南站`、`上海虹桥站` 这类交通枢纽要能归到所在城市，否则跨城路线会被当作同城；
    但 `北京大学`、`上海研发中心` 不行——机构名里的城市前缀不代表这是个出行端点。
    """

    if not value:
        return None
    normalized = normalize_location_name(value)
    if normalized in KNOWN_LOCATION_NAMES:
        return normalized
    lowered = value.strip().lower()
    if lowered in EN_KNOWN_LOCATION_NAMES:
        return lowered
    return _city_of_transport_hub(normalized)


def _city_of_transport_hub(value: str) -> str | None:
    for city in KNOWN_LOCATION_NAMES:
        if not value.startswith(city) or value == city:
            continue
        remainder = value[len(city) :]
        if remainder.endswith(_TRANSPORT_HUB_SUFFIXES):
            return city
    return None


def are_distinct_known_cities(origin: str, destination: str) -> bool:
    """两端都能定位到已知城市且城市不同时，才算跨城出行。"""

    origin_city = resolve_city_key(origin)
    destination_city = resolve_city_key(destination)
    if origin_city is None or destination_city is None:
        return False
    return origin_city != destination_city


def has_known_location_prefix(value: str) -> bool:
    """允许 `上海外滩`、`浦东新区外滩` 这类带前缀的地标写法。"""

    for landmark in KNOWN_LANDMARK_NAMES | KNOWN_LOCATION_NAMES:
        if value == landmark or not value.endswith(landmark):
            continue
        prefix = value[: -len(landmark)]
        if prefix in KNOWN_LOCATION_NAMES or prefix.endswith(ADMIN_DIVISION_SUFFIXES):
            return True
    return False
